---
  - hosts: app
    become: true
    vars:
      fav:
        fruit: mango
    roles:
      - {role: apache, tags: www } 
      - {role: php, tags: ['www', 'php'] } 
      - {role: frontend, when: ansible_os_family == 'RedHat', tags: devopsdemo}
    tags: 
      - frontend
