---
  users:
    admin:
      uid: 5001
      shell: /bin/bash
      home: /home/admin
      state: present
    josemart:
      uid: 1001
      shell: /bin/bash
      home: /home/josemart
      state: present
    mikeflin:
      uid: 1002
      shell: /bin/bash
      home: /home/mikeflin
      state: present
    dojo:
      state: absent  
      
  systems:
    packages:
      - ntp 
      - tree 
      - vim 

  fav:
    color: yellow
    fruit: guava
    
  dbconn:
    host: 192.168.61.14
    user: devops
    pass: password
    db: devopsdemo
    
  haproxy_backend_servers:
    - name: app1
      address: 192.168.61.12:80
    - name: app2
      address: 192.168.61.13:80
  haproxy_backend_httpchk: ''
  
  mysql_root_password: password
  mysql_databases:
    - name: devopsdemo
      encoding: latin1
      collation: latin1_general_ci
  
  mysql_users:
    - name: devops
      host: "%"
      password: password
      priv: "devopsdemo.*:ALL"
  mysql_bind_address: '0.0.0.0'
  