---
# defaults file for frontend
  app:      # You make the variables 
    version: 1.5
    env: LOCALDEV
    
  fav:
    color: white
    fruit: orange
    car: chevy
    laptop: toshiba
  
  dbconn:
    host: localhost
    user: root
    pass: changeme
    db: devopsdemo